### ISSUE TITLE
Is this real?

### ISSUE THREAD

**Issue by pryshrm** [yako-dev/flutter-settings-ui#100]
Is this project real? It has no working example, no clear documentation. The code sample doesn't compile. What am I missing?

**Comment by pryshrm** [comment]
Where is this CustomTile? DevicePreview.appBuilder?

**Comment by Chris-Shivom** [comment]
For Custom Tile see this: https://github.com/yako-dev/flutter-settings-ui/issues/93#issuecomment-933460707

**Comment by Chris-Shivom** [comment]
actually this works better: https://github.com/yako-dev/flutter-settings-ui/issues/96#issuecomment-968181812


You can find the package here: https://pub.dev/packages/flutter_settings_ui

**Comment by yadaniyil** [comment]
Hey @pryshrm @Chris-Shivom . There is a new 2.0.0 version of the package, could you please if your issue is fixed there? Thanks :)
