### ISSUE TITLE
settings_ui: ^2.0.1 trailing icon add

### ISSUE THREAD

**Issue by spstrademark** [yako-dev/flutter-settings-ui#103]
Hello,

on the latest version of settings_ui ( 2.0.1 ) how can we add a trailing icon to the SettingsTile ?
Older versions had a trailing property.

Best regards,
Stanko

**Comment by RusKryzhanovskiy** [comment]
Hi, @spstrademark.
Thank you for the bug report.
This functionality will be available in a future release.

**Comment by yadaniyil** [comment]
@spstrademark please check 2.0.2 version that was just released
