### ISSUE TITLE
How add trailing widget in 2.0.1

### ISSUE THREAD

**Issue by johanlantz** [yako-dev/flutter-settings-ui#108]
I have just updated to 2.0.1 and I do not know how to add a trailing checkmark anymore, like in this ticket:
https://github.com/yako-dev/flutter-settings-ui/pull/4

Or for instance in this example from Whatsapp
![IMG_583A4E012759-1](https://user-images.githubusercontent.com/7461655/151167172-2fdf00ec-2944-458a-95e4-5bc6b0910599.jpeg)

**Comment by RusKryzhanovskiy** [comment]
Hey, @johanlantz! Thank you for the question!
This functionality will be available in 2.0.2

**Comment by yadaniyil** [comment]
@johanlantz please check 2.0.2 version that was just released

**Comment by johanlantz** [comment]
It works, thanks for the quick turnaround. Also awesome that you now have the .navigation option so I do not have to implement it myself anymore. Great work.
