### ISSUE TITLE
Too dark background on Android

### ISSUE THREAD

**Issue by ginnyTheCat** [yako-dev/flutter-settings-ui#11]
The background of the settings is nearly black while the AppBar is more dark grey. I think this is a Android thing only because iOS has this black darkmode. Is there any way to change this? I would really like to use it in my app but this currently holds me back.

**Comment by chitgoks** [comment]
i was about to create a new issue for this one as well. the background is just black but normal components in flutter use dark gray as its background.

**Comment by yadaniyil** [comment]
Added `backgroundColor` attribute in `SettingsList`
