### ISSUE TITLE
Outdated code example in ```README.md``` file

### ISSUE THREAD

**Issue by ShehanAT** [yako-dev/flutter-settings-ui#119]
The example code shown in the ```Basic Usage``` section of the README.md file no longer work with version ```2.0.2```
This is because the ```title``` field of the ```SettingsSection```, ```SettingsTile``` and ```SettingsTile.switchTile``` objects require an object of type ```Widget?``` which is conflicting with the default ```String``` type that is provided. 

There are also non-existent fields in the ```SettingsSection```, ```SettingsTile``` and ```SettingsTile.switchTile``` objects such as ```subtitle``` and ```switchValue``` in version ```2.0.2```

**Comment by ilovelinux** [comment]
Issue has been solved, please close the issue :smile:
