### ISSUE TITLE
Is it possible to have the same design for Android 

### ISSUE THREAD

**Issue by AlmogRnD** [yako-dev/flutter-settings-ui#120]
The ios design is really good and I wanted to know if it's possible to set that as the default for Andiords as well?

**Comment by MohamedFBoussaid** [comment]
Seems it is possible 
I didnt test it but here the example that was given: 
https://github.com/yako-dev/flutter-settings-ui/issues/76#issuecomment-888366537

**Comment by MohamedFBoussaid** [comment]
It is possible to do it this way :
`   child: SettingsList(
          **platform: DevicePlatform.iOS,**
          sections: [
            SettingsSection(
              title: const Text('Example'),
              tiles: <SettingsTile>[
                SettingsTile.switchTile(
              title: const Text('Lock app in background'),
              leading: const Icon(Icons.phonelink_lock),
              switchValue: lockInBackground,
              onToggle: (bool value) {
                setState(() {
                  lockInBackground = value;
                  notificationsEnabled = value;
                });
              },
            ),
          ],
        ),
          ],
        );
     `

**Comment by AlmogRnD** [comment]
Working great thanks
