### ISSUE TITLE
scrollbar location on wide screens

### ISSUE THREAD

**Issue by thomas725** [yako-dev/flutter-settings-ui#121]
On wide screens (web & linux desktop version), where the content doesn't use the whole width of the browser window, the scrollbar stays within the borders of the reduced width content. It should be at the right end of the browser window instead.

A usability problem resulting from this: Since the bars left and right of the content are not part of the scroll-able area, positioning the mouse pointer over one of them and using the mouse-wheel does not scroll the page.

**Comment by yadaniyil** [comment]
Thanks @thomas725. The fix will be published with next package update
