### ISSUE TITLE
use DefaultTextStyle.merge() to replace DefaultTextStyle()

### ISSUE THREAD

**Issue by stephen-yu-gh** [yako-dev/flutter-settings-ui#123]
My custom text styles are overridden by DefaultTextStyle(). Please consider to use DefaultTextStyle.merge() instead.

**Comment by M-ixai-L** [comment]
Hey, @stephen-yu-gh,  I'm sorry, but I have not found this problem, could you describe the problem in more detail or provide a code example where the styles are overridden?

**Comment by stephen-yu-gh** [comment]
I try to reproduce the bug today and find the newest version (2.0.2) is OK. 

This issue can be closed. Sorry to trouble you. 

---

Here was the problem. I am sure it has changed from 2.0.1 to 2.0.2.

![2 0 1](https://user-images.githubusercontent.com/7233253/174945066-36e0cfe3-7c62-4468-a37d-98666dc22a03.png)

![2 0 2](https://user-images.githubusercontent.com/7233253/174945083-68220781-2090-4eba-b75d-deb7c44c4d8f.png)
