### ISSUE TITLE
The following assertion was thrown building AndroidSettingsTile(dirty, dependencies: [MediaQuery, SettingsTheme]):

### ISSUE THREAD

**Issue by darix15** [yako-dev/flutter-settings-ui#124]
i have this error when i try this plugin,

======== Exception caught by widgets library =======================================================
The following assertion was thrown building AndroidSettingsTile(dirty, dependencies: [MediaQuery, SettingsTheme]):
Failed assertion: boolean expression must not be null

this is my code :

SettingsTile.switchTile(
                      title: const Text('Remote Data'),
                      leading: const Icon(Icons.language),
                      description: const Text("Envoyer les donnees de la base de donnees en ligne"),
                      enabled: provider.sendRemote,
                      onToggle: (value) {
                        log("WakeLock ${provider.wakeLockState}");
                        provider.changeSendData = value;
                      },
                      initialValue: provider.wakeLockState,
                    ),

**Comment by M-ixai-L** [comment]
Hey @darix15 , сan you try this code?   
          SettingsTile.switchTile(
              title: 'Remote Data',
              leading: Icon(Icons.language),
              subtitle: "Envoyer les donnees de la base de donnees en ligne",
              enabled: provider.sendRemote,
              onToggle: (value) {
                setState(() {
                  log("WakeLock ${provider.wakeLockState}");
                  provider.changeSendData = value;
                });
              },
              switchValue: provider.changeSendData,
            ),

**Comment by darix15** [comment]
Thanks i fix this issue
