### ISSUE TITLE
Margin is not used on Android/Fucsia/Linux

### ISSUE THREAD

**Issue by ilovelinux** [yako-dev/flutter-settings-ui#131]
Hi,
I'm using this package to draw my settings UI. I spent some time trying to use `SettingsSection`'s `margin` parameter  without any result. When I had a look at the package code, I discovered that margin is not used by `AndroidSettingsSection` which is the widget returned by `SettingsSection` when the platform is Android/Fucsia/Linux ([reference](https://github.com/yako-dev/flutter-settings-ui/blob/d8d97b23474fc0697334812e9dcfc4d5adb5d071/lib/src/sections/settings_section.dart#L27-L34))

I think that margin should be used by `AndroidSettingsSection` too, or at least is should be mentioned on docs.

**Comment by hhamja** [comment]
me too, not working margin in SettingsSection....
So, I lost a lot of time

**Comment by dpalmeira** [comment]
Same to me, I cannot set in Android a smaller space between items... Any workaround?

**Comment by yadaniyil** [comment]
Hey, thanks for the issue. This bug is fixed and will be deployed soon.
