### ISSUE TITLE
Description style of `SettingsTile` on iOS

### ISSUE THREAD

**Issue by leavjenn** [yako-dev/flutter-settings-ui#135]
Hi, thanks for this useful lib, it helps me a lot.

There's one issue though: the `description` of `SettingsTile` on iOS is not the same as the native one. It's more like the description of `SettingsSection`. Below is a screenshot of iOS 15 Screen Time setting page. Please notice the descriptions of the top 5 items, and the descriptions of the items below them.

![IMG_4446](https://user-images.githubusercontent.com/13175621/176999134-2661740e-d2d6-4aa9-9d9b-3f5e01482c80.jpeg)

**Comment by yadaniyil** [comment]
Thanks, @leavjenn. This will be added in the next version of the lib
