### ISSUE TITLE
can not change the background color

### ISSUE THREAD

**Issue by leogildo10** [yako-dev/flutter-settings-ui#14]
hey there nice work, is there an option to change the SettingsSection and SettingsTile background color?

**Comment by Akora-IngDKB** [comment]
Currently, there isn't an option for that yet. 
I'll try and see a possible work around.

**Comment by yadaniyil** [comment]
For now, you can change only the background color of SettingsList

**Comment by anoop4real** [comment]
This is a nice package but would need some options to style the tiles sections etc. very much needed.... as sometimes default ones doesnt match with the apps theme.

**Comment by Akora-IngDKB** [comment]
What kind of styles exactly? TextStyle, background colors, shapes, which of them?

**Comment by anoop4real** [comment]
TextStyle and Background Color

**Comment by Akora-IngDKB** [comment]
> For now, you can change only the background color of SettingsList

I took a look at the code and I realized the `backgroundColor` of `SettingsList` is only applied in Dark Mode.
It has no effect in Light Mode.

**Comment by Akora-IngDKB** [comment]
I've opened a [PR](https://github.com/yako-dev/flutter-settings-ui/pull/17) which allows you to make some customization to some of the texts and also change the active color of the switch as requested in  this issue - #7 .

**Comment by anoop4real** [comment]
Great.. let me know once this is merged and active

**Comment by oriollpz** [comment]
The `backgroundColor` isn't working yet, I change it but it doesn't work.

**Comment by Akora-IngDKB** [comment]
> The `backgroundColor` isn't working yet, I change it but it doesn't work.
> 
> **Update**: I just realized that the `backgroundColor` works in Dark Mode, but not in Light Mode.

Yeah true. It's a bug in the existing version but it has been fixed in [commit](https://github.com/yako-dev/flutter-settings-ui/pull/17/commits/eae721f03ea4c3b044485cc6397d13d7c27d193b) of [PR](https://github.com/yako-dev/flutter-settings-ui/pull/17).

**Comment by ghenry** [comment]
Just spotted this too on Android when brightness is light, `backgroundColor` is hard coded as grey. Need white :-)

**Comment by Akora-IngDKB** [comment]
> Just spotted this too on Android when brightness is light, `backgroundColor` is hard coded as grey. Need white :-)

Yhup. It's an existing bug. It's been fixed in a proposed [PR](https://github.com/yako-dev/flutter-settings-ui/pull/17) - [commit](https://github.com/yako-dev/flutter-settings-ui/pull/17/commits/eae721f03ea4c3b044485cc6397d13d7c27d193b).

**Comment by ghenry** [comment]
Going to merge it and do a new release?

**Comment by Akora-IngDKB** [comment]
Surely but @yadaniyil has to do that. He is the one with the pub access.

**Comment by ghenry** [comment]
Could someone with rights to a new release with the PR? Thanks.

**Comment by Akora-IngDKB** [comment]
@ghenry I doubt.
Unless it's released as a new package not as an update of this package

**Comment by ghenry** [comment]
If the original author is now not reachable or no longer interested in maintaining then it's probably best to release a replacement on pub.dev

Shame.

**Comment by RusKryzhanovskiy** [comment]
Sorry for the delay. 
Now we have finished the update and this functionality will be available in version 0.4.0.
