### ISSUE TITLE
Disabled SettingsTile not showing as disabled in web

### ISSUE THREAD

**Issue by lucasoares** [yako-dev/flutter-settings-ui#145]
Disable SettingsTile is not changing its appearance on Web devices.

Example (language is disabled) running on Chrome:
![image](https://user-images.githubusercontent.com/10624972/197404362-ea073b65-0c23-4772-99ec-2a03c3cad3ea.png)

The same screen with the same attributes on Android:
![image](https://user-images.githubusercontent.com/10624972/197404525-a3763604-f5f5-4083-bb58-cd9a118d2db1.png)

**Comment by yadaniyil** [comment]
Thanks for the issue @lucasoares, this will be deployed shortly in the next version, please reopen the issue if you will have this issue again in new version.
