### ISSUE TITLE
Long text in the settings tile does not wrap

### ISSUE THREAD

**Issue by mingsai** [yako-dev/flutter-settings-ui#15]
Either the settings tile should grow automatically or the text should shrink to fit. If not possible already would you accept a PR to get this done?

**Comment by philofred** [comment]
Along these lines, currently the text on the left side of the settings tile (the title) does wrap, but I'd prefer the ability to not have it wrap and instead use ellipsis to truncate or some such.  Also, the wrapping currently gets cut off if you have large fonts on ios.

**Comment by yadaniyil** [comment]
For Android, a lot of text will wrap and tile will grow in height. This is how Material tile work. 
For iOS, I didn't find any double-lined tiles in native settings so I added `overflow: TextOverflow.ellipsis` for iOS tiles.
