### ISSUE TITLE
How about adding `flutter pub add cupertino_icons` to Readme?

### ISSUE THREAD

**Issue by kaedeee** [yako-dev/flutter-settings-ui#161]
Thank you for making this awesome package.

I have one request.
This flutter package needs to be installed one external package, `cupertino_icons`. 
So, how about writing like the below line in the Readme.md ?
`flutter pub add cupertino_icons`

If developers don't add this,  `CupertinoIcons.chevron_forward` won't be shown.
So, It'll help them, especially, beginners.

<img width="200" alt="Simulator Screen Shot - iPhone X - 2023-01-12 at 18 32 25" src="https://user-images.githubusercontent.com/55743370/212030749-53b135f4-0894-4e2e-a45b-5c82a95e9685.png">

Best regards.

**Comment by yadaniyil** [comment]
That is a great point @kaedeee , I wonder how the package has been existing for years but nobody mentioned this before :)
It seems like everyone uses cupertino_icons. I will add this to the readme, thanks!
