### ISSUE TITLE
This attribute can be opened about ListView ”scrollController”

### ISSUE THREAD

**Issue by Zvirtuey** [yako-dev/flutter-settings-ui#164]
SettingsList=> add "scrollController"
![image](https://user-images.githubusercontent.com/20436938/212619112-788effad-1bfb-48b4-845c-0e813dc5bb94.png)

**Comment by yadaniyil** [comment]
Hey @Zvirtuey, thanks for the suggestion, it's in the dev branch already and will be published soon

**Comment by Zvirtuey** [comment]
> Hey @Zvirtuey, thanks for the suggestion, it's in the dev branch already and will be published soon

Can release the new version!
