### ISSUE TITLE
Slider not available anymore?

### ISSUE THREAD

**Issue by bbence84** [yako-dev/flutter-settings-ui#167]
I saw commits for the sliderTile type, but I don't see it in the main branch anymore... Any ideas? :) Thanks!

**Comment by yadaniyil** [comment]
Hey @bbence84 
There are 2 PRs for the sliderTile:
https://github.com/yako-dev/flutter-settings-ui/pull/68
https://github.com/yako-dev/flutter-settings-ui/pull/88
but they have never been merged into the master.

For now, I don't have the intention to add the sliderTile, but this should be possible by extending the AbstractSettingsTile on your end. Please create a new issue if you'll have problems with it.
