### ISSUE TITLE
A strange question icon appears

### ISSUE THREAD

**Issue by lwj1994** [yako-dev/flutter-settings-ui#169]
![image](https://user-images.githubusercontent.com/10978048/221585089-95ccd556-e4ff-450e-a358-1826e091cabf.png)

Inspector show that is a  RichText ，but i can't find it。how can i dismiss this question mark

lib version:  2.0.2
flutter sdk:  Flutter 3.7.3 
build plateform:  macOS 13.2

**Comment by yadaniyil** [comment]
Hey @lwj1994, please add cupertino_icons to your pubspec.yaml and try again. Let me know if it helps

**Comment by lwj1994** [comment]
> Hey @lwj1994, please add cupertino_icons to your pubspec.yaml and try again. Let me know if it helps

thanks it solved
