### ISSUE TITLE
Arrow Icon not working

### ISSUE THREAD

**Issue by youcci** [yako-dev/flutter-settings-ui#175]
I get this weird Box with a question mark
![CleanShot 2023-04-15 at 01 16 07](https://user-images.githubusercontent.com/13952789/232169337-34bcf962-b81d-4950-bf2f-4afd7592a1aa.png)
Anyone an idea how to fix it?

**Comment by lilipads** [comment]
I ran into the same issue. How did you fix it?

**Comment by jakobhec** [comment]
I needed to add https://pub.dev/packages/cupertino_icons in my `pubspec.yaml` to fix this.

**Comment by dominic-schmid** [comment]
Thanks, that fixed it.
