### ISSUE TITLE
Icons in Windows

### ISSUE THREAD

**Issue by SenexTech** [yako-dev/flutter-settings-ui#183]
I believe the icons are not displaying properly on Windows.  Is there a fix for this?
![Image1](https://github.com/yako-dev/flutter-settings-ui/assets/45659887/e129d404-376e-4970-a468-6c9017868c4a)

**Comment by RemcoSchrijver** [comment]
Can you attach the code coming with this example?

**Comment by yadaniyil** [comment]
Hey @SenexTech, are those icons cupertino icons? If yes, then you need to add cupertino_icons to the pubspec.yaml

**Comment by SenexTech** [comment]
RemcoSchrijver,
The icons are now showing. Sorry, but I have no idea when they started working so I don't know if it was something I did.  Here is the code anyways:

 // GENERAL SECTION ****************************
            Padding(
              padding: const EdgeInsets.only(
                  left: 15,
                  bottom: 5,
                  right: 0,
                  top: 10), //apply padding to all four sides
              child:
                  Text("general", style: Theme.of(context).textTheme.titleLarge)
                      .tr(),
            ),
            Card(
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(10),
                //set border radius more than 50% of height and width to make circle
              ),
              margin: const EdgeInsets.all(8),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Padding(
                    padding: const EdgeInsets.only(top: 5.0),
                    child: ListTile(
                      title: Text("language",
                              style: Theme.of(context).textTheme.titleLarge)
                          .tr(),
                      subtitle: Text("language_sub",
                              style: Theme.of(context).textTheme.bodySmall)
                          .tr(),
                      leading: const Icon(Icons.language),
                      trailing: const Icon(Icons.edit),
                      onTap: () {
                        Navigator.push(
                            context,
                            MaterialPageRoute(
                                builder: (context) => const LanguageView()));
                      },
                    ),
                  ),
                  Divider(
                    height: 20,
                    thickness: 1,
                    indent: 20,
                    endIndent: 0,
                    color: Theme.of(context).dividerColor,
                  ),
                  Padding(
                    padding: const EdgeInsets.only(bottom: 5.0),
                    child: ListTile(
                      title: Text("themes",
                              style: Theme.of(context).textTheme.titleLarge)
                          .tr(),
                      subtitle: Text("select_theme",
                              style: Theme.of(context).textTheme.bodySmall)
                          .tr(),
                      leading: const Icon(Icons.imagesearch_roller),
                      trailing: const Icon(Icons.edit),
                      onTap: () {
                        Navigator.push(
                            context,
                            MaterialPageRoute(
                                builder: (context) => const ThemesView()));
                      },
                    ),
                  )
                ],
              ),
            ),

**Comment by SenexTech** [comment]
yadaniyil,
They are Material Icons.  Again, as above they are now working

**Comment by yadaniyil** [comment]
That's weird. Please reopen if you will have some more info about it @SenexTech
