### ISSUE TITLE
SettingsTile.switchTile only works for swipe

### ISSUE THREAD

**Issue by Swepilot** [yako-dev/flutter-settings-ui#19]
Looking to implement this package in my project and it looks promising. Good work! 

For some reason though the `SettingsTile.switchTile` switch only works if I swipe it, just tapping it does not toggle the switch.

This is on iOS, have not tried Android behavior.

**Comment by Akora-IngDKB** [comment]
It works fine for Android.
I think this behaviour is with iOS and Web only.

**Comment by Swepilot** [comment]
Please consider this for future release as "tap" is normally working on iOS.

**Comment by Akora-IngDKB** [comment]
Okay.
I'll look into it for a fix :+1:

**Comment by Akora-IngDKB** [comment]
I've proposed a fix in [commit](https://github.com/yako-dev/flutter-settings-ui/pull/17/commits/3ad8f73a007aaed9c8877b0cab7bc8cf5ed1cb95) of my open [pull request](https://github.com/yako-dev/flutter-settings-ui/pull/17).

**Comment by Swepilot** [comment]
Further to this... I looked in more detail and could see that the `onTap` was called but only once, if tapping another time it wasn't. I managed to get it all to work if the `onTap` included a `setState()`

**Comment by yadaniyil** [comment]
I checked and seems like a tap on the switch works fine. @Swepilot I'll appreciate a more detailed issue description. Feel free to reopen the issue.
