### ISSUE TITLE
iOS navigation tile: trailing chevron shows a questionmark

### ISSUE THREAD

**Issue by dominic-schmid** [yako-dev/flutter-settings-ui#195]
I'm not sure why this is happening as all the other icons and tiles are working just fine.
My `pubspec.yaml` is using `uses-material-design: true` and turning this off naturally results in all icons being a question mark.

### Issue

![image](https://github.com/yako-dev/flutter-settings-ui/assets/45590457/3c4c9a36-148d-4d63-a089-f380d56a4461)

### Code

```dart
SettingsTile.navigation(
    onPressed: (context) async {
        // action
    },
    leading: const Icon(Icons.language),
    title: Text(dg.settingsLanguage),
    value: Text(languages[Intl.getCurrentLocale()]!['nativeName']!),
),
```

I'm using version 2.0.2. Is there an obvious thing I'm missing here?

**Comment by xpirt** [comment]
yes, you're missing `cupertino_icons` package.

**Comment by dominic-schmid** [comment]
Thanks, that fixed it!
