### ISSUE TITLE
Tablet/iPad support

### ISSUE THREAD

**Issue by jacekkrasowski** [yako-dev/flutter-settings-ui#2]
Great lib! But have you thought of bigger screens support?
Of course everyone can fork and do it on their own but that is a nice to have feature.

Cheers

**Comment by RusKryzhanovskiy** [comment]
Hi, @jacekkrasowski!  Sorry for the REALLY big delay.

You can use:
```dart
return SettingsList(
    contentPadding: const EdgeInsets.symmetric(horizontal: 180),
);
```


And it will look something like this:

<img src="https://user-images.githubusercontent.com/25484375/107493344-29791680-6b96-11eb-8dca-96178578dfa6.png" data-canonical-src="https://user-images.githubusercontent.com/25484375/107493344-29791680-6b96-11eb-8dca-96178578dfa6.png" width="600" />
