### ISSUE TITLE
Crash when using lambda for onTap: callback on iOS

### ISSUE THREAD

**Issue by woelmer** [yako-dev/flutter-settings-ui#20]
When I use lambda syntax for SettingsTile callback `onTap: () => print('test')` vs anonymous function syntax `onTap: () { print('test'); }` I get an exception thrown `type '() => void' is not a subtype of type '() => Future<void>'`. I believe this is because SettingsTile onTap is defined as a VoidCallback or void Function() and it is being assigned to CupertinoSettingsItem.onPress which is a PressOperationCallback or Future\<void\>.

Full example tile that will cause crash:
`SettingsTile(
    title: 'testing',
    onTap: () => print('testing'),
  )`

**Comment by Akora-IngDKB** [comment]
Have you tried `onTap: () async => print('testing'),)`

**Comment by woelmer** [comment]
Yes that does work, so perhaps the onTap type should be changed.

**Comment by Akora-IngDKB** [comment]
Yeah.
This is a simple fix.
I've pushed the fix onto an existing PR (#17).

**Comment by RusKryzhanovskiy** [comment]
Sorry for the delay. 
Now we have finished the update and this functionality will be available in version 0.4.0.
