### ISSUE TITLE
Settings not showing up in iOS

### ISSUE THREAD

**Issue by RicardoRB** [yako-dev/flutter-settings-ui#23]
Hi all!

For any reason, my settings in iOS in release mode is not showing it up.
  settings_ui: ^0.3.0

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.3, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 4.0)
[✓] Android Studio (version 3.6)
[✓] Connected device (1 available)

• No issues found!

![photo_2020-06-09_18-01-30](https://user-images.githubusercontent.com/3050311/84171697-6b881080-aa7b-11ea-8ac6-a7be275c9b26.jpg)

**Comment by Akora-IngDKB** [comment]
Can we see the part of the code containing the SettingsList?

**Comment by RicardoRB** [comment]
@Akora-IngDKB 
it is a bit long:


    return SettingsList(
      sections: [
        SettingsSection(
          tiles: [
            SettingsTile(
              title: userLogged.email == null ? '' : userLogged.email,
              subtitle: AppLocalizations.of(context)
                      .trans('PROFILE_TEXT_SPECIFIC_DIET') +
                  ': ' +
                  (userLogged.specificDiet != null
                      ? AppLocalizations.of(context)
                          .trans(userLogged.specificDiet?.toString())
                      : AppLocalizations.of(context)
                          .trans('PROFILE_TEXT_NONE')) +
                  '\n' +
                  AppLocalizations.of(context)
                      .trans('PROFILE_TEXT_REQUISITE_DIET') +
                  ': ' +
                  (userLogged.requisiteDiet != null
                      ? AppLocalizations.of(context)
                          .trans(userLogged.requisiteDiet?.toString())
                      : AppLocalizations.of(context)
                          .trans('PROFILE_TEXT_NONE')) +
                  '\n' +
                  AppLocalizations.of(context).trans('PROFILE_TEXT_ALLERGENS') +
                  ': ${userLogged?.allergens != null ? userLogged?.allergens?.length : 0}',
              leading: Icon(Icons.person),
              onTap: () {
                widget._analytics.logEvent(
                  name: 'profile_page_btn_user_info',
                );
              },
            ),
          ],
        ),
        SettingsSection(
          title: AppLocalizations.of(context).trans('PROFILE_TEXT_ABOUT_YOU'),
          tiles: [
            SettingsTile(
              title: AppLocalizations.of(context)
                  .trans('PROFILE_BTN_EDIT_FOOD_PREFERENCES'),
              subtitle: "",
              leading: Icon(Icons.fastfood),
              onTap: () {
                widget._analytics.logEvent(
                  name: 'profile_page_btn_edit_food',
                );
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) =>
                        QuestionPage(widget._analytics, false),
                  ),
                );
              },
            ),
            SettingsTile(
              title:
                  AppLocalizations.of(context).trans('PROFILE_BTN_YOUR_ORDERS'),
              subtitle: "",
              leading: Icon(FontAwesomeIcons.shoppingBag),
              onTap: () {
                widget._analytics.logEvent(
                  name: 'profile_page_btn_your_orders',
                );
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) => OrderListPage(widget._analytics),
                  ),
                );
              },
            ),
            userLogged.courier
                ? SettingsTile(
                    title: 'Courier',
                    subtitle: "",
                    leading: Icon(FontAwesomeIcons.biking),
                    onTap: () {
                      Navigator.push(
                        context,
                        MaterialPageRoute(
                          builder: (context) => CourierListPage(),
                        ),
                      );
                    },
                  )
                : null,
          ],
        ),
        SettingsSection(
          title: AppLocalizations.of(context).trans('PROFILE_TEXT_ACCOUNT'),
          tiles: [
            SettingsTile(
              title: AppLocalizations.of(context).trans('PROFILE_BTN_ABOUT_US'),
              subtitle: "",
              leading: Icon(Icons.thumb_up),
              onTap: () {
                widget._analytics.logEvent(
                  name: 'profile_page_btn_about_us',
                );
                launch('https://.com/');
              },
            ),
            SettingsTile(
              title: AppLocalizations.of(context).trans('PROFILE_BTN_FEEDBACK'),
              subtitle: "",
              leading: Icon(Icons.feedback),
              onTap: () {
                widget._analytics.logEvent(
                  name: 'profile_page_btn_feedback',
                );
                launch(
                    'mailto:info@getfoodin.com?subject=App Feedback&body=Feedback');
              },
            ),
            SettingsTile(
              title: AppLocalizations.of(context).trans('PROFILE_BTN_OUR_BLOG'),
              subtitle: "",
              leading: Icon(Icons.receipt),
              onTap: () {
                widget._analytics.logEvent(
                  name: 'profile_page_btn_our_blog',
                );
                launch('https://getfoodin.com/blog/');
              },
            ),
            SettingsTile(
              title: AppLocalizations.of(context).trans('PROFILE_TEXT_SHARE'),
              subtitle: "",
              leading: Icon(Icons.share),
              onTap: () {
                widget._analytics.logEvent(
                  name: 'profile_page_btn_share',
                );
                Share.share('https://getfoodin.com');
              },
            ),
          ],
        ),
        SettingsSection(
          title: AppLocalizations.of(context).trans('PROFILE_BTN_LOGOUT'),
          tiles: [
            SettingsTile(
              title: AppLocalizations.of(context).trans('PROFILE_BTN_LOGOUT'),
              subtitle: "",
              leading: Icon(Icons.exit_to_app),
              onTap: () {
                widget._analytics.logEvent(
                  name: 'profile_page_btn_log_out',
                );
                _profileBloc.add(ProfileLogoutRequest());
              },
            ),
          ],
        ),
      ],
    );

**Comment by Akora-IngDKB** [comment]
> @Akora-IngDKB
> it is a bit long:
> 
> ```
> return SettingsList(
>   sections: [
>     SettingsSection(
>       tiles: [
>         SettingsTile(
>           title: userLogged.email == null ? '' : userLogged.email,
>           subtitle: AppLocalizations.of(context)
>                   .trans('PROFILE_TEXT_SPECIFIC_DIET') +
>               ': ' +
>               (userLogged.specificDiet != null
>                   ? AppLocalizations.of(context)
>                       .trans(userLogged.specificDiet?.toString())
>                   : AppLocalizations.of(context)
>                       .trans('PROFILE_TEXT_NONE')) +
>               '\n' +
>               AppLocalizations.of(context)
>                   .trans('PROFILE_TEXT_REQUISITE_DIET') +
>               ': ' +
>               (userLogged.requisiteDiet != null
>                   ? AppLocalizations.of(context)
>                       .trans(userLogged.requisiteDiet?.toString())
>                   : AppLocalizations.of(context)
>                       .trans('PROFILE_TEXT_NONE')) +
>               '\n' +
>               AppLocalizations.of(context).trans('PROFILE_TEXT_ALLERGENS') +
>               ': ${userLogged?.allergens != null ? userLogged?.allergens?.length : 0}',
>           leading: Icon(Icons.person),
>           onTap: () {
>             widget._analytics.logEvent(
>               name: 'profile_page_btn_user_info',
>             );
>           },
>         ),
>       ],
>     ),
> ```

@RicardoRB This does not really provide a good insight into the problem.
Can you show us a snippet of the parent containing the `SettingsList` and **the error in the console** too?

**Comment by RicardoRB** [comment]
> SettingsList

Unfortunately, I can not see the error because I develop with linux and I launch it with codemagic in both platforms.

This is the parent:

return Scaffold(
      extendBodyBehindAppBar: true,
      appBar: FloatingAppBar(),
      key: _scaffoldKey,
      body: BlocProvider<ProfileBloc>(
        create: (context) => _profileBloc,
        child: BlocListener(
          bloc: _profileBloc,
          listener: (BuildContext context, state) {
            if (state is ProfileLogOutLoadFailure) {
              SnackBarUtils.showError(context,
                  message: AppLocalizations.of(context)
                      .trans("PROFILE_TXT_ERROR_LOGOUT"));
            }

            if (state is ProfileUserAnonymous ||
                state is ProfileLogOutLoadSuccess) {
              Navigator.pushAndRemoveUntil(
                  context,
                  MaterialPageRoute(
                    builder: (context) => IntroPage(widget._analytics),
                  ),
                  (Route<dynamic> route) => false);
            }
          },
          child: BlocBuilder<ProfileBloc, ProfileState>(
              builder: (BuildContext context, ProfileState state) {
            if (state is ProfileUserLoggedState) {
              return _settingProfile(state.user);
            }

            if (state is ProfileLoadInProgress) {
              return Center(child: CircularProgressIndicator());
            }

            if (state is ProfileLoadFailure) {
              return Center(
                child: Retry(
                  onPressed: () =>
                      _profileBloc.add(ProfileCurrentUserRequest()),
                ),
              );
            }
            return Container();
          }),
        ),
      ),
    );

**Comment by Akora-IngDKB** [comment]
Oops. The error log would've help a lot.

I'm guessing the `_settingProfile(state.user)` contains the `SettingsList` snippet you posted earlier on.
Is it the direct child of the `_settingProfile(state.user)` widget or it's part of it's children?

**Comment by RicardoRB** [comment]
Yes, you are right, _settingProfile(state.user) is the code that I used before.

The direct widget is a "BlocBuilder" but Scaffold as a real widget :)

**Comment by Akora-IngDKB** [comment]
Okay.
But is there a way you can debug locally and view the error log?

**Comment by RicardoRB** [comment]
@Akora-IngDKB There you go, I did I trick and this is:

flutter: When the exception was thrown, this was the stack:

flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)

flutter: #1      CupertinoSettingsSection.build (package:settings_ui/src/cupertino_settings_section.dart:43:38)

flutter: #2      StatelessElement.build (package:flutter/src/widgets/framework.dart:4576:28)

flutter: #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)

flutter: #4      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)

flutter: #5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)

flutter: #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)

flutter: ...     Normal element mounting (39 frames)

flutter: #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)

flutter: #46     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)

flutter: #47     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1162:36)

flutter: #48     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1147:20)

flutter: #49     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2607:19)

flutter: #50     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1140:11)

flutter: #51     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:354:23)

flutter: #52     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1866:58)

flutter: #53     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:918:15)

flutter: #54     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1866:13)

flutter: #55     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:343:5)

flutter: #56     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:489:5)

flutter: #57     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:219:19)

flutter: #58     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:262:19)

flutter: #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)

flutter: #60     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:135:11)

flutter: #61     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:375:11)

flutter: #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)

flutter: #63     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:452:13)

flutter: #64     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1444:12)

flutter: #65     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1353:20)

flutter: #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)

flutter: #67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)

flutter: #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)

flutter: #69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)

flutter: #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)

flutter: #71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)

flutter: #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)

flutter: #73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)

flutter: #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)

flutter: #75     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)

flutter: #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)

flutter: #77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)

flutter: #78     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)

flutter: #79     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:111:13)

flutter: #80     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)

flutter: #81     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:246:13)

flutter: #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)

flutter: #83     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:11)

flutter: #84     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:484:7)

flutter: #85     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)

flutter: #86     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:399:14)

flutter: #87     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1630:7)

flutter: #88     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)

flutter: #89     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:402:19)

flutter: #90     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:13)

flutter: #91     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)

flutter: #92     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)

flutter: #93     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)

flutter: #94     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)

flutter: #98     _invoke (dart:ui/hooks.dart:261:10)

flutter: #99     _drawFrame (dart:ui/hooks.dart:219:3)

flutter: (elided 3 frames from dart:async)

flutter:

**Comment by RicardoRB** [comment]
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-06-09 at 10 54 21](https://user-images.githubusercontent.com/3050311/84182721-24098080-aa8b-11ea-8997-28a0a78deb52.png)

**Comment by RicardoRB** [comment]
Ok, it is because of the null that I'm adding... hahaha

but I don't know why the [?] in iOS

**Comment by Akora-IngDKB** [comment]
> Ok, it is because of the null that I'm adding... hahaha
> 
> but I don't know why the [?] in iOS

Not sure it is.
The second log points to the file in the library itself.

I'm trying to reproduce the error from my end.
I'll get back with what I find.

**Comment by Akora-IngDKB** [comment]
The problem is coming from this part of your code:
```
userLogged.courier
            ? SettingsTile(
                title: 'Courier',
                subtitle: "",
                leading: Icon(FontAwesomeIcons.biking),
                onTap: () {
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (context) => CourierListPage(),
                    ),
                  );
                },
              )
            : null,
```
You are essentially returning `SettingsTile = null` when that condition is false. The library tries to render the tile by accessing it's properties which then causes the 'Null Exception'.

Do this instead:
```
if (userLogged.courier)
             SettingsTile(
                title: 'Courier',
                subtitle: "",
                leading: Icon(FontAwesomeIcons.biking),
                onTap: () {
                  Navigator.push(
                    context,
                    MaterialPageRoute(
                      builder: (context) => CourierListPage(),
                    ),
                  );
                },
              )
```

**Comment by RicardoRB** [comment]
@Akora-IngDKB 

Yes, that's what I saw hehe. I think it would be nice to create a pull request to filter null :)

**Comment by Akora-IngDKB** [comment]
I don't think that will really be necessary. It can be easily handled by the user.
I don't think the package has to do that.

Instead of using the condition short hand `cond ? yes : no`, just using an `if` without the `{ }` will do the job.

**Comment by RicardoRB** [comment]
Hmmm, I do not totally agree. I close the issue in any case. Thanks for your everything @Akora-IngDKB !
