### ISSUE TITLE
Dark Theme in CupertinoApp

### ISSUE THREAD

**Issue by Gebes** [yako-dev/flutter-settings-ui#25]
When I have an CupertinoApp and I use the SettingsList widget, it still only uses the Material Theme class, which has the light brightness as default.
However, using the CupertinoApp widget, and having dark mode enabled, sets only the CupertinoTheme class to dark and not the Theme class.

This gives back a weird result, where the NavBar is dark, but the SettingsList is still light.

**Comment by Trulsmatias** [comment]
Maybe it should use MediaQuery.of(context).platformBrightness instead?

**Comment by emce** [comment]
or any of non-context like `SchedulerBinding.instance?.window.platformBrightness`?

**Comment by RusKryzhanovskiy** [comment]
Hi @Gebes 
The dark theme is available as of version 2.0
