### ISSUE TITLE
Android: Ripple effect on SettingsTile missing

### ISSUE THREAD

**Issue by Merthan** [yako-dev/flutter-settings-ui#27]
Would expect the ripple effect to be there, at least when onTap != null

**Comment by Akora-IngDKB** [comment]
This should be a problem on iOS only.
Android should already have ripple effect.

**Comment by yadaniyil** [comment]
@Merthan, sorry for the delay.
Ripple effect on SettingsTile for Android available in version `settings_ui: ^0.5.0`
