### ISSUE TITLE
Can not change Dark mode manually?

### ISSUE THREAD

**Issue by SimonRijn** [yako-dev/flutter-settings-ui#29]
I can't find an option to activate dark mode manually, can this be correct? Also, don't get it done with a provider because the plugin doesn't support that in the settings.

Anyone have an idea for this?

**Comment by AjayShanker-geek** [comment]
I don't know if this will help because I started learning only a week.

Under `main.dart,` your return `theme:` should have `brightness: Brightness.dark` in ThemeData class.

**Comment by yadaniyil** [comment]
@SimonRijn You can use @AjayShanker-geek's advice.
Or you can always wrap any widget in Theme.

```dart
Theme(
  data: ThemeData.dark(),
  child: SettingsList(...)
)
```
