### ISSUE TITLE
Is this package still updated?

### ISSUE THREAD

**Issue by houdayec** [yako-dev/flutter-settings-ui#30]
Hey,

Thanks for this package. I've seen really interesting PR with backgroundColor fix and more customization which is to me, very important, to make you UI consistent.

Do you plan in making a release for this package? Otherwise, give rights to new contributors to make this package still alive...

Thanks!

**Comment by ghenry** [comment]
Anyone?

**Comment by RusKryzhanovskiy** [comment]
@houdayec, @ghenry 
We are very glad that you like our library. 
Soon a new version will be available which we are currently working on.
