### ISSUE TITLE
Package not updated on pub.dev

### ISSUE THREAD

**Issue by Akora-IngDKB** [yako-dev/flutter-settings-ui#31]
From commit [99faae32](https://github.com/yako-dev/flutter-settings-ui/commit/99faae32d3d7efc1bf78d856eb6284ea9f24768c) the package has been updated to v0.4.0 but it's still v0.3.0 on [pub.dev](https://pub.dev/packages/settings_ui).

@yadaniyil Can this be clarified?

**Comment by RusKryzhanovskiy** [comment]
@Akora-IngDKB  today or tomorrow we'll put out an update. Sorry for the delay.

**Comment by yadaniyil** [comment]
Today or tomorrow, we'll put out an update. Sorry for the delay.
