### ISSUE TITLE
Option to save/load settings in shared preferences

### ISSUE THREAD

**Issue by garry-jeromson** [yako-dev/flutter-settings-ui#34]
Awesome project- a real time saver and nice, clean code.

It'd be great to add an option to some settings tiles (e.g. switch tiles) that would provide options to automatically save the value to shared preferences. I'd suggest starting with switch tiles, using the settings label as the default preferences key when saving, and providing a configuration option to set a non-default key. Settings for other tile types would require some more discussion.

Is this something anyone else would find valuable? If there's enough interest and a willingness to accept the feature request, I can put together a pull request.

**Comment by Akora-IngDKB** [comment]
Personally, I feel this will be an overwork for the package seeing it was make to ease Settings UI dev.
There are other packages available as well with this functionality (like [this](https://pub.dev/packages/shared_preferences_settings)).

But if the community feels it's great to have it here, then I think we can go ahead with it.

**Comment by fredecodes** [comment]
I use shared_preferences package separately from settings_ui package.  Others may prefer to use different packages or code to manage their settings, so I think settings_ui should remain as is..

**Comment by garry-jeromson** [comment]
> There are other packages available as well with this functionality (like [this](https://pub.dev/packages/shared_preferences_settings)).

Yeah, that package was the original inspiration and would be the template I'm suggesting; using shared_preferences internally, such that users wouldn't have to add boilerplate to every setting item to load the value and save it on changes. But like you say @fredecodes, it'd only be worth doing if it could be sufficiently generalised to be useful for a lot of users.

**Comment by yadaniyil** [comment]
@garry-jeromson 
I think that everyone should choose the storage method according to their needs. 
This plugin is a plugin about the UI.

I consider it as needless functionality, at this moment.

**Comment by ThraaxSession** [comment]
Hi together, if there is no integration. Do you have any example how to use your lib with shared_preferences?
