### ISSUE TITLE
There are multiple hardcoded colors. Could they be paramaterized?

### ISSUE THREAD

**Issue by MiguelSOliveira** [yako-dev/flutter-settings-ui#38]
https://github.com/yako-dev/flutter-settings-ui/blob/master/lib/src/colors.dart#L9

Here for example, the `iosTileDarkColor` is hardcoded but then the background color of the `SettingsList` is not, so they end up not matching.

Am I missing something or am I correct in saying that these colors can not be set?

I think more customization would be awesome.. Maybe not showing the dividers for example, as well?

**Comment by azazadev** [comment]
any update ?

**Comment by nietsmmar** [comment]
It seems like the owner of this package is not longer developing on it. Maybe we should fork it and start a new one.

**Comment by yadaniyil** [comment]
Hey @MiguelSOliveira @azazadev @nietsmmar . There is a new 2.0.0 version of the package, could you please if your issue is fixed there? Thanks :)
