### ISSUE TITLE
Can you publish v5 to pub.dev?

### ISSUE THREAD

**Issue by deeprobin** [yako-dev/flutter-settings-ui#42]
I need this for my app.
Thank you 👍

**Comment by Akora-IngDKB** [comment]
> I need this for my app.
> Thank you 👍 

Got published today. [settings_ui](https://pub.dev/packages/settings_ui)

**Comment by RusKryzhanovskiy** [comment]
@deeprobin thank you for reminding me. V5 already on pub.dev
