### ISSUE TITLE
Why does onPressed have a BuildContext parameter?

### ISSUE THREAD

**Issue by Akora-IngDKB** [yako-dev/flutter-settings-ui#44]
In the `v0.5.0`, the `onTap` which was a `VoidCallback` has been deprecated in favor of `onPressed` which has `dynamic Function(BuildContext)` signature.

With the `SettingsTile` behaving more or less like a `ListTile`, it feels inconsistent to have a `BuildContext` on the `onPressed` callback.

**Why do we need that `context` parameter**?

**Comment by RusKryzhanovskiy** [comment]
@Akora-IngDKB we need this in order to make it possible for example to open dialogs and keep them working correctly.
