### ISSUE TITLE
Is there any way to hide the arrow on the far right?

### ISSUE THREAD

**Issue by nrikiji** [yako-dev/flutter-settings-ui#49]
Thanks for the great plugin.

I would like to display the version of the application in the settings screen. 
Is there any way to hide the arrow on the far right?

**Comment by thongvo109** [comment]
You can use Container() in props name **trailing** of widget **SettingsTile**

**Comment by nrikiji** [comment]
Thank you for your answer. I'm sorry, can you give me a sample source?

**Comment by thongvo109** [comment]
> Thank you for your answer. I'm sorry, can you give me a sample source?

Hi,
<img width="630" alt="Screen Shot 2021-02-01 at 3 05 10 PM" src="https://user-images.githubusercontent.com/64881072/106430846-fbf9e200-649e-11eb-9d5c-938d4fd72fea.png">

**Comment by nrikiji** [comment]
thanks

**Comment by nuzelac** [comment]
Btw I used `iosChevron: null` instead of `trailing: ...` in the new version.
