### ISSUE TITLE
BUG: CupertinoSettingsItem allows toggle when disabled

### ISSUE THREAD

**Issue by fredecodes** [yako-dev/flutter-settings-ui#51]
In the GestureDetector method of CupertinoSettingsItem, the onTap handler has the following code to toggle the switch, however this code does not checked if widget.enabled is true.  This has the effect of allowing toggle switches to have their onToggle callback called when they are disabled, which shouldn't happen IMO.  My workaround is to check the disabled condition again in my callback, but ideally this should be fixed in the lib.

```
if (widget.type == SettingsItemType.toggle) {
  setState(() {
    _checked = !_checked;
    widget.onToggle(_checked);
  });
}
```

I think the fix is just to change the first line as follows:
```
if (widget.type == SettingsItemType.toggle && widget.enabled) {
```

**Comment by Akora-IngDKB** [comment]
Thanks for pointing it out.
