### ISSUE TITLE
Double trailing when trailing is setted in iOS

### ISSUE THREAD

**Issue by RicardoRB** [yako-dev/flutter-settings-ui#56]
In iOS SettingsTile [[CupertinoSettingsItem](https://github.com/yako-dev/flutter-settings-ui/blob/master/lib/src/cupertino_settings_item.dart)] when you set trailing but not iosChevron, you will see duplicated trailing.

## Expected Behavior
When trailing is set, not show iOS Chevron.

## Current Behavior
Double trailing

## Possible Solution
if (widget.iosChevron != null && widget.trailing!= null) {
...
}

## Steps to Reproduce
```dart
SettingsTile(
              title: 'Blabla',
              leading: Icon(Icons.food_bank_outlined),
              ),
              trailing: Icon(Icons.keyboard_arrow_right),
              onPressed: (value) {
              },
            ),
```

## Context (Environment)
iOS device

**Comment by RusKryzhanovskiy** [comment]
Hi @RicardoRB, will be fixed in `0.7.0`
