### ISSUE TITLE
Change tiles parameter inside SettingsSection to List of Widget

### ISSUE THREAD

**Issue by brizaldi** [yako-dev/flutter-settings-ui#57]
Currently tiles parameter needs a `List<SettingsTile>`, this become a problem if we need to wrap `SettingsTile` with something else (for example: Bloc or other custom wrapper) since the type will become widget and isn't compatible with SettingsTile

**Comment by RusKryzhanovskiy** [comment]
Hi @brizaldi at the moment you can wrap anything you want in `CustomSection` 

```dart
CustomSection(
          child: YourWidget(
            child: SettingsTile(
              title: 'Terms of Service',
              leading: Icon(Icons.description),
            ),
          ),
        ),
```

**Comment by brizaldi** [comment]
what i'm proposing is maybe something like this:
```
SettingsSection(
  title: 'Title',
  tiles: <Widget>[
    SettingsTile(),
    BlocListener<...>(        // wrap it with bloc
      listener: ...,
      child: SettingsTile(),
    ),
    ...
  ],
),
```

that makes it and easier to customize than using `CustomSection`, because when we use `CustomSection` we have to create the section UI from scratch rather than following the `SettingSection` UI
