### ISSUE TITLE
Should we use the Android 11 settings screen design?

### ISSUE THREAD

**Issue by juliansteenbakker** [yako-dev/flutter-settings-ui#62]
The current Android design differs from the Android 11 settings design as shown in the picture below. I think it would be nice if we can update the design to match the latest version of Android. 
![Screenshot_1615385727](https://user-images.githubusercontent.com/20091319/110642951-d6ee4280-81b3-11eb-889b-decd86f19d74.png)

**Comment by Akora-IngDKB** [comment]
Where does the design differ?

The android settings uses the widgets which follow material design. How do we update them to match what's in the image?

**Comment by yadaniyil** [comment]
@juliansteenbakker agree. We will need to update it to the latest android, thanks :)

**Comment by yadaniyil** [comment]
Hey @juliansteenbakker. There is new 2.0.0 version of the package, could you please check if new UI looks the same as laters android settings UI. Thanks :)
