### ISSUE TITLE
flutter pub get only returns ^0.6.0

### ISSUE THREAD

**Issue by ScottWallace** [yako-dev/flutter-settings-ui#65]
Running flutter pub get only returns version 0.6.0, and manually changing the `pubspec.yaml` to `settings_ui: ^0.7.0` results in this error:

`Because[your app] depends on settings_ui ^0.7.0 which doesn't match any versions, version solving failed.`

Tried to fix this by fixing the flutter cache with `flutter pub cache repair`, to no avail. 

Is there some pub.dev setting that has to be made to get this version registered with flutter pub?

**Comment by yadaniyil** [comment]
Hi @ScottWallace. Unfortunately, version 0.7.0 was not uploaded to the pub, but we released 1.0.0-nullsafety.1 a couple of days ago, you should try this one. Let me know if it works for you.

**Comment by yadaniyil** [comment]
Actually 1.0.0-nullsafety.2
