### ISSUE TITLE
Margin broken when upgrading to v0.6

### ISSUE THREAD

**Issue by Androz2091** [yako-dev/flutter-settings-ui#66]
Hello :wave:
Thank you for this great project, it makes the creation of simple settings UI very easy! But I upgraded my app to v0.6 and got this problem. Can you take a look at it? Thank you

## **v0.4**:
<img height="400px" src="https://user-images.githubusercontent.com/42497995/111794001-17417500-88c6-11eb-94f8-5d64cdfffab0.jpg" />

## **v0.6**:
<img height="400px" src="https://user-images.githubusercontent.com/42497995/111794008-190b3880-88c6-11eb-9511-e71f2cf29502.jpg" />

**Comment by he0119** [comment]
I think it is due to <https://github.com/yako-dev/flutter-settings-ui/issues/54>.

**Comment by Androz2091** [comment]
Thank you, I think I will wait for v0.7.0 to be released, and I will stay on v0.4.0 as I don't use null-safety at this time

**Comment by TheLastGimbus** [comment]
Hi there! This is still an issue :grimacing: Why can't `title` just be a widget? Like `subtitle`...

**Comment by RusKryzhanovskiy** [comment]
@Androz2091, @TheLastGimbus sorry for the delay!

@TheLastGimbus, parameters `Widget? titleWidget` and `Widget? subtitleWidget` will be available in version `1.0.1`

@Androz2091 this is related to the Flutter. To be more specific - to the `ListView.builder`. You can use the `contentPadding` parameter to set the same values for Android and iOS.
