### ISSUE TITLE
Expected a value of type 'List<Widget> error in web device

### ISSUE THREAD

**Issue by awlobo** [yako-dev/flutter-settings-ui#70]
Hi, I'm just starting with Flutter so I'm not sure if it's related to the library or not.
I'm using Flutter 2.0.2, Dart 2.12.1 and the Prerelease: 1.0.0-nullsafety.2 version (I guess I have to use that version because of null safety).

The library is working perfectly in the android device, but not in the web device (chrome) and it's throwing this error `Expected a value of type 'List<Widget>', but got one of type 'List<Widget?>'`:

![error](https://user-images.githubusercontent.com/10184549/112368121-071d0180-8cdb-11eb-9b21-e9636ba89517.PNG)

My code is basically like the example code:

![code](https://user-images.githubusercontent.com/10184549/112368180-1603b400-8cdb-11eb-90ff-650171f1600b.PNG)

If you need more info just me  know. Thanks in advance.

**Comment by yadaniyil** [comment]
Should be fixed in the ^1.0.0 version. Please check and reopen if it's not working.
