### ISSUE TITLE
Platforms are setting colors diferently from each other and from ThemeData.

### ISSUE THREAD

**Issue by jcnils** [yako-dev/flutter-settings-ui#77]
Hello,

When I build flutter for web, settings_ui gets some elements from the "ThemeData" (Tile Title, divider), but not all of them.
![web_settings](https://user-images.githubusercontent.com/961151/117868797-8b2a4900-b289-11eb-9b9a-82ebde79e882.png)

When I do the same for an android emulator (system-images;android-30;google_apis_playstore;x86), it seems to only get some dividers from the same Theme.
![android](https://user-images.githubusercontent.com/961151/117869155-faa03880-b289-11eb-836c-777377e3b0cb.png)

I wonder if I am missing something when setting the Theme, it would be nice to have it following the rest of the theme of the app. 

As a workaround, It seems I can set most of those styles under settings-ui by hand, except for the tile background that behaves completely different in each platform.

The code from the images above.
```Dart
SettingsList(
      backgroundColor: theme.scaffoldBackgroundColor,
      sections: [
		SettingsSection(
				  title: 'Info',
				  titleTextStyle: theme.textTheme.headline1,
				  tiles: [
				    SettingsTile(
				      title: 'Name',
				      subtitle: name,
				      leading: Icon(
				        Icons.person_outline,
				      ),
				      onPressed: (BuildContext context) {
				        //code
				      },
				    ),
				    SettingsTile(
				      title: 'Email',
				      subtitle: email,
				      leading: Icon(Icons.alternate_email),
				      onPressed: (BuildContext context) {
				        //code
				      },
				    ),
				    SettingsTile(
				      title: 'Phone',
				      subtitle: phone,
				      leading: Icon(Icons.phone),
				      onPressed: (BuildContext context) {
				        //code
				      },
				    ),
				  ],
				),
				...
```

I think it might be a mix of this 
https://github.com/yako-dev/flutter-settings-ui/issues/61
and this
https://github.com/yako-dev/flutter-settings-ui/issues/38

Please let me know if I can provide any more info, or help.

Thanks.

----
Updates

The "SettingsTile" Name, Email and Phone are using from ThemeData:
|Parameter | Web | Android |
|--- |--- |--- |
| title | ? | textTheme.subtitle1 | 
| subtitle | ? | |
| switch | ? | |
| divider | dividerColor | dividerColor |
| divider2 | - | ? |
| tile background | ListTileTheme | ListTileTheme |
| leading | [Colors.black45 / ListTileTheme](https://github.com/yako-dev/flutter-settings-ui/blob/7ec5c762831388903ffe962e8ef8ad89f5e64a25/lib/src/cupertino_settings_item.dart#L314) | Colors.black45/ListTileTheme |

*I will update this table as I find them

**Comment by yadaniyil** [comment]
Hey @jcnils. There is a new 2.0.0 version of the package, could you please if your issue is fixed there? Thanks :)
