### ISSUE TITLE
iOS Title text getting cut off in version 1.0.0

### ISSUE THREAD

**Issue by fredecodes** [yako-dev/flutter-settings-ui#78]
In the 1.0.0 release, my longer iOS titles are getting ellipsis treatment where they used to not.  I'd really like the ability to control this so that the full text can be displayed when there is room.  If the subtitle string is short and the title text is long, both should not be given 50% of the screen (assuming that's what is happening?).  See pics below for a comparison of the same screen with 0.6.0 vs 1.0.0:

![060](https://user-images.githubusercontent.com/15000050/118673593-fb672c00-b7ad-11eb-906f-a1b519fa037c.png)
![100](https://user-images.githubusercontent.com/15000050/118673596-fbffc280-b7ad-11eb-9d08-e276d2b6b942.png)

**Comment by uenx** [comment]
Same problem here.
We have to downgrade to **0.6.0** (and unsounding null-safety!）for the time being.

**Comment by devon** [comment]
```
const _spacer = Expanded(child: SizedBox.shrink());
```

The `_spacer` add an Expanded, maybe it shouldn't.

**Comment by ayushin** [comment]
please merge!

**Comment by RobertBouten** [comment]
Can this be merged? Or can I help in anyway to do so? This would fix my issue with this as well. Thnx

**Comment by fredecodes** [comment]
This issue is NOT fixed with latest code on master, I just verified.  So I believe that the spacer issue was not related to this bug, and this issue should not have been closed.  A new issue has been opened for the same problem though, so I guess I'll comment there.
