### ISSUE TITLE
can't input other Widget above SettingsList

### ISSUE THREAD

**Issue by calvinsug** [yako-dev/flutter-settings-ui#8]
Container(
        padding: EdgeInsets.all(10.0),
        child: Column(
          children: <Widget>[
                //other Widget,
                SettingsList(
      sections: [
        SettingsSection(
          tiles: [ 
            SettingsTile(
              title: 'Document Backup',
              leading: Icon(Icons.backup),
              onTap: () {
                print('backup');
              },
            ),
          ],
        ),
      ],
    );

When i add another my custom UI above SettingsTile, 
The settings_ui doesnt' appear at all, can i add my other Custom UI before i put the custom_ui ?

**Comment by Akora-IngDKB** [comment]
Wrap your ```SettingsList``` widget in an ```Expanded```

**Comment by Akora-IngDKB** [comment]
Place your `SettingsList` in an `Expanded` widget.
```
Container(
    padding: EdgeInsets.all(10),
        child: Column(
            children: <Widget>[
            Placeholder(),   // Your other widget
            // Your SettingsList in an expanded widget
            Expanded(
              child: SettingsList(
                sections: [
                  SettingsSection(
                    title: 'Common',
                    tiles: [
                      SettingsTile(
                        title: 'Language',
                        subtitle: 'English',
                        leading: Icon(Icons.language),
                        onTap: () {
                          Navigator.of(context).push(MaterialPageRoute(
                              builder: (BuildContext context) =>
                                  LanguagesScreen()));
                        },
                      ),
                      SettingsTile(
                          title: 'Environment',
                          subtitle: 'Production',
                          leading: Icon(Icons.cloud_queue)),
                    ],
                ),
            ),
          ],
        ),
      ),
```

**Comment by yadaniyil** [comment]
Thanks, @Akora-IngDKB. The solution is really simple and very usual for Flutter.
@calvinsug you should wrap `SettingsList` in `Expanded`, as `SettingsList` is a `ListView`.
