### ISSUE TITLE
SwitchTile does not toggle

### ISSUE THREAD

**Issue by AliAlhajji** [yako-dev/flutter-settings-ui#80]
I am using version 1.0.0.

The Switch Tile does not toggle to the other value when I click on it. It changes for a moment, then returns back to the same value assigned in `switchValue` property.

This is my code:
![image](https://user-images.githubusercontent.com/35175106/119568590-45f03600-bdb6-11eb-914b-0584ae626c43.png)

It always print the opposite value of `switchValue`, which means it's changing and then goes back to the original value:

![image](https://user-images.githubusercontent.com/35175106/119569361-52c15980-bdb7-11eb-974b-afa12437020d.png)

p.s.: I am using it inside a StatelessWidget, if that helps.

**Comment by fredecodes** [comment]
The switchTile doesn't take care of toggling the value, you have to do that yourself in the onToggle handler, eg:

`onToggle: (value) {_settings.publicBirthday = value;}`

Though you wouldn't do it like that, you'd more likely call some function that changes state such that your widget gets updated, and then it uses the new value.  This is what I do for example with a stateful widget that contains the value being toggled:
`switchValue: sendNotification,
 onToggle: (value) => setState(() => sendNotification = value),`

**Comment by AliAlhajji** [comment]
> 
> 
> The switchTile doesn't take care of toggling the value, you have to do that yourself in the onToggle handler, eg:
> 
> `onToggle: (value) {_settings.publicBirthday = value;}`
> 
> Though you wouldn't do it like that, you'd more likely call some function that changes state such that your widget gets updated, and then it uses the new value. This is what I do for example with a stateful widget that contains the value being toggled:
> `switchValue: sendNotification, onToggle: (value) => setState(() => sendNotification = value),`

I guessed that I have to use StatefulWidget if I want to change it, right?
The example on the repo page uses StatelessWidget, which is a bit confusing.

**Comment by fredecodes** [comment]
You can do it either with stateful widget (like my example pasted above), or stateless.  With stateless though, your onToggle handler would call some function outside of the widget which has the effect of forcing the widget to update due to some inherited state change.

**Comment by RusKryzhanovskiy** [comment]
Hi, @AliAlhajji !
Sorry for the delay!

I think you should debug your code. 
This code works as expected:

```dart
bool value = true;
Widget build(BuildContext context) {
...
SettingsTile.switchTile(
              title: 'Enable Notifications',
              enabled: notificationsEnabled,
              leading: Icon(Icons.notifications_active),
              switchValue: value,
              onToggle: (value) {
                setState(() {
                  this.value = value;
                });
              },
            ),
 ...
}
```
