### ISSUE TITLE
Custom content as SettingsTile

### ISSUE THREAD

**Issue by obrunsmann** [yako-dev/flutter-settings-ui#85]
We have the requirement to add some custom content between the settings tiles for explaination. Here are two examples from iOS:

![IMG_4420](https://user-images.githubusercontent.com/763812/124094802-64062180-da59-11eb-8b25-202715257679.PNG)
![IMG_4419](https://user-images.githubusercontent.com/763812/124094809-65cfe500-da59-11eb-97ec-49b77e8b5c02.PNG)

I am of course willing to contribute this request as a PR, just wanted to check out with you guys if you have any requirements or ideas for that? 
Maybe someone has a corresponding Android Screenshot while I am most familar to iOS devices.

**Comment by RusKryzhanovskiy** [comment]
Hi, @obrunsmann!
The `CustomTile` widget was implemented. You can use it since version `1.0.1`

```dart
 CustomTile(
              child: Container(
                color: Color(0xFFEFEFF4),
                padding: EdgeInsetsDirectional.only(
                  start: 14,
                  top: 12,
                  bottom: 30,
                  end: 14,
                ),
                child: Text(
                  'You can setup the language you want',
                  style: TextStyle(
                    color: Colors.grey.shade700,
                    fontWeight: FontWeight.w400,
                    fontSize: 13.5,
                    letterSpacing: -0.5,
                  ),
                ),
              ),
            ),
```

![Screenshot 2021-07-29 at 17 45 22](https://user-images.githubusercontent.com/25484375/127512990-080c77c4-c8d0-45f6-b3c9-e11979ddbf73.png)

**Comment by rteitge** [comment]
Would like to use that, but pub.dev is at version 1.0.0
