### ISSUE TITLE
iOS switchTile (CupertinoSettingsItem) diverges from native behaviour

### ISSUE THREAD

**Issue by lucaspal** [yako-dev/flutter-settings-ui#87]
The behaviour of the iOS-looking switch tile is not what an iOS user would expect. 

**Expected behaviour**: Only the switch is tappable
**Actual behaviour**: The entire row is tappable

This is not only a confusing behaviour for an iOS user, but this also makes harder placing a `leading` widget that has a different `onTap` behaviour, since the user could, by mistake, trigger the switch tap action instead of the one from the leading element.

**Comment by RusKryzhanovskiy** [comment]
@lucaspal fixed in version `1.0.1`! 
Thanks for your propousal!

**Comment by lucaspal** [comment]
@RusKryzhanovskiy That's amazing. I will integrate it in the project I am working on and I can give you feedback, if any. 

Do you have an idea of when `1.0.1` will be available?
