### ISSUE TITLE
SwitchTile onToggle doesnt fire all the time

### ISSUE THREAD

**Issue by chitgoks** [yako-dev/flutter-settings-ui#9]
Weird behavior im encountering. the onToggle gets called when it's either one of the toggled values.

but not both.

the switchValue is a boolean variable where the default value is set via an await function where i get the value saved in storage.

**Comment by vtumino** [comment]
You need to rebuild the widget when the state changes, look at this: 
https://stackoverflow.com/a/55440602/7798398

**Comment by chitgoks** [comment]
i forgot to reply. got to work this. i did a workaround
