### ISSUE TITLE
Old version on pub.dev/packages/?

### ISSUE THREAD

**Issue by u2tall** [yako-dev/flutter-settings-ui#91]
I'm trying to get version 1.0.1 via my pubspec.yaml, but it only has 1.0.0. Can this be updated? the 1.0.1 update has a great fix I would love to implement.
I'm pretty new to flutter packages so maybe I'm doing this wrong. Thanks so much for your time, this package is amazing.

**Comment by yadaniyil** [comment]
Hey @u2tall . There is a new 2.0.0 version of the package. Please try it and let me know if you find any issues, we will fix them ASAP
