### ISSUE TITLE
Version 1.0.1 not available on pub.dev

### ISSUE THREAD

**Issue by shi-rudo** [yako-dev/flutter-settings-ui#93]
The last available version on pub.dev does not match the git repo. According to changelog.md, the version on github is 1.0.1 and in pub.dev 1.0.0.

[1.0.0] - [April 13, 2021]
https://pub.dev/packages/settings_ui/changelog

[1.0.1] - [Jul 28, 2021]
https://github.com/yako-dev/flutter-settings-ui/blob/master/CHANGELOG.md

I am currently overriding my pubsec.yml dev for 1.0.1, but I would like to avoid this.

**Comment by agostinofiscale** [comment]
Is there any update about this? Seems like there is still the previous version on pub.dev

**Comment by YouROK** [comment]
Please deploy

**Comment by grgn23** [comment]
Please deploy

**Comment by agostinofiscale** [comment]
> Please deploy

Sadly there are no updates, but if it can help you, you can just get the package from this repository:

    settings_ui:
        git:
          url: https://github.com/yako-dev/flutter-settings-ui.git
          ref: master


I hope this can help someone :)

**Comment by Kurosawa** [comment]
If this problem is not solved, the sample code won't work. This is because there is a CustomTile implementation in 1.0.1 and the sample code uses it.

**Comment by yadaniyil** [comment]
Hey @shi-rudo @agostinofiscale @YouROK @grgn23 @Kurosawa . There is a new 2.0.0 version of the package, could you please if your issue is fixed there? Thanks :)
