### ISSUE TITLE
v1.0.0 Title gets cut off

### ISSUE THREAD

**Issue by DragonSlayer88** [yako-dev/flutter-settings-ui#96]
Title gets cut off if its too long. There is still space as I have no subtitle. Can this be expanded? 

Also title max lines does nothing. If i set that to 2 or anything really, it doesnt work.

**Comment by RemcoSchrijver** [comment]
+1 I have the same problem, would be great if this get's fixed.

**Comment by fumin65** [comment]
This problem seems to have been fixed in v1.0.1.
However, it has not been deployed to pub.dev yet.

#93

**Comment by malikdoksoz** [comment]
`  settings_ui:
    git:
      url: https://github.com/yako-dev/flutter-settings-ui.git
      ref: master`

**You can use it like this**
The new version does not appear in pub.dev. Needs to be fixed

**Comment by fredecodes** [comment]
No, you just need to reference the new package, which is called flutter_settings_ui:
  flutter_settings_ui: ^2.0.1

**Comment by malikdoksoz** [comment]
> No, you just need to reference the new package, which is called flutter_settings_ui: flutter_settings_ui: ^2.0.1

I mentioned this package. (settings_ui)

**Comment by fredecodes** [comment]
> This problem seems to have been fixed in v1.0.1. However, it has not been deployed to pub.dev yet.
> 
> #93

Did you test this and verify that it is fixed?  I am still seeing this bug with latest code on master (after manually applying the ListThemeData compile fix needed for Flutter 2.8).  Note that this bug was originally submitted awhile ago (see https://github.com/yako-dev/flutter-settings-ui/issues/78) and marked as fixed but doesn't appear that it actually was fixed.

**Comment by yadaniyil** [comment]
Hey @DragonSlayer88 @RemcoSchrijver @fumin65 @sylvain-flt @malikdoksoz @fredecodes . There is a new 2.0.0 version of the package, could you please if your issue is fixed there? Thanks :)
