### ISSUE TITLE
Trailing parameter not working

### ISSUE THREAD

**Issue by nietsmmar** [yako-dev/flutter-settings-ui#98]
No matter what I set in `trailing`, it is never shown.

**Comment by yadaniyil** [comment]
Hey @nietsmmar . There is a new 2.0.0 version of the package, could you please if your issue is fixed there? Thanks :)

**Comment by nietsmmar** [comment]
@yadaniyil Thanks! Sadly it does not work as described here https://github.com/yako-dev/flutter-settings-ui/issues/115
